// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	credentials "github.com/versent/saml2aws/v2/helper/credentials"
)

// Helper is an autogenerated mock type for the Helper type
type Helper struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0
func (_m *Helper) Add(_a0 *credentials.Credentials) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*credentials.Credentials) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: serverURL
func (_m *Helper) Delete(serverURL string) error {
	ret := _m.Called(serverURL)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(serverURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: serverURL
func (_m *Helper) Get(serverURL string) (string, string, error) {
	ret := _m.Called(serverURL)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (string, string, error)); ok {
		return rf(serverURL)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(serverURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(serverURL)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(serverURL)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SupportsCredentialStorage provides a mock function with given fields:
func (_m *Helper) SupportsCredentialStorage() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsCredentialStorage")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewHelper creates a new instance of Helper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *Helper {
	mock := &Helper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
