// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Prompter is an autogenerated mock type for the Prompter type
type Prompter struct {
	mock.Mock
}

// Choice provides a mock function with given fields: prompt, options
func (_m *Prompter) Choice(prompt string, options []string) string {
	ret := _m.Called(prompt, options)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, []string) string); ok {
		r0 = rf(prompt, options)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RequestSecurityCode provides a mock function with given fields: pattern
func (_m *Prompter) RequestSecurityCode(pattern string) string {
	ret := _m.Called(pattern)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(pattern)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// StringRequired provides a mock function with given fields: pr
func (_m *Prompter) StringRequired(pr string) string {
	ret := _m.Called(pr)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(pr)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
