// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	playwright "github.com/playwright-community/playwright-go"
	mock "github.com/stretchr/testify/mock"
)

// Response is an autogenerated mock type for the Response type
type Response struct {
	mock.Mock
}

// AllHeaders provides a mock function with given fields:
func (_m *Response) AllHeaders() (map[string]string, error) {
	ret := _m.Called()

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Body provides a mock function with given fields:
func (_m *Response) Body() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Finished provides a mock function with given fields:
func (_m *Response) Finished() {
	_m.Called()
}

// Frame provides a mock function with given fields:
func (_m *Response) Frame() playwright.Frame {
	ret := _m.Called()

	var r0 playwright.Frame
	if rf, ok := ret.Get(0).(func() playwright.Frame); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(playwright.Frame)
		}
	}

	return r0
}

// HeaderValue provides a mock function with given fields: name
func (_m *Response) HeaderValue(name string) (string, error) {
	ret := _m.Called(name)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HeaderValues provides a mock function with given fields: name
func (_m *Response) HeaderValues(name string) ([]string, error) {
	ret := _m.Called(name)

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Headers provides a mock function with given fields:
func (_m *Response) Headers() map[string]string {
	ret := _m.Called()

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// HeadersArray provides a mock function with given fields:
func (_m *Response) HeadersArray() (playwright.HeadersArray, error) {
	ret := _m.Called()

	var r0 playwright.HeadersArray
	var r1 error
	if rf, ok := ret.Get(0).(func() (playwright.HeadersArray, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() playwright.HeadersArray); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(playwright.HeadersArray)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JSON provides a mock function with given fields: v
func (_m *Response) JSON(v interface{}) error {
	ret := _m.Called(v)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Ok provides a mock function with given fields:
func (_m *Response) Ok() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Request provides a mock function with given fields:
func (_m *Response) Request() playwright.Request {
	ret := _m.Called()

	var r0 playwright.Request
	if rf, ok := ret.Get(0).(func() playwright.Request); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(playwright.Request)
		}
	}

	return r0
}

// SecurityDetails provides a mock function with given fields:
func (_m *Response) SecurityDetails() (*playwright.ResponseSecurityDetailsResult, error) {
	ret := _m.Called()

	var r0 *playwright.ResponseSecurityDetailsResult
	var r1 error
	if rf, ok := ret.Get(0).(func() (*playwright.ResponseSecurityDetailsResult, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *playwright.ResponseSecurityDetailsResult); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*playwright.ResponseSecurityDetailsResult)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServerAddr provides a mock function with given fields:
func (_m *Response) ServerAddr() (*playwright.ResponseServerAddrResult, error) {
	ret := _m.Called()

	var r0 *playwright.ResponseServerAddrResult
	var r1 error
	if rf, ok := ret.Get(0).(func() (*playwright.ResponseServerAddrResult, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *playwright.ResponseServerAddrResult); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*playwright.ResponseServerAddrResult)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Status provides a mock function with given fields:
func (_m *Response) Status() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// StatusText provides a mock function with given fields:
func (_m *Response) StatusText() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Text provides a mock function with given fields:
func (_m *Response) Text() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// URL provides a mock function with given fields:
func (_m *Response) URL() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewResponse interface {
	mock.TestingT
	Cleanup(func())
}

// NewResponse creates a new instance of Response. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewResponse(t mockConstructorTestingTNewResponse) *Response {
	mock := &Response{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
